version: '3'

services:
  apifant-valigator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8081/health" ]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 5s