version: '3'

services:
  apifant-repo:
    image: nginx:alpine-slim
    volumes:
      - ./build:/usr/share/nginx/html

  apifant-valigator:
    depends_on:
      - apifant-repo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GOARCH=arm64
    environment:
      DEVMODE: 1
    ports:
      - 8081:8081
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8081/health" ]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 5s

  apifant-editor:
    depends_on:
      - apifant-valigator
    restart: always
    # image: ghcr.io/huk-coburg/apifant-editor:latest
    build:
      context: ../apifant-editor
      dockerfile: Dockerfile
    environment:
      VALIGATOR_SCHEME: http
      VALIGATOR_HOST: apifant-valigator
      VALIGATOR_PORT: 8081
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8080/index.html" ]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 5s
