name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate Docker Image Tag
      run: echo "ghcr.io/huk-coburg/apifant-valigator:$(date +%Y%m%d-%H%M%S)" >> $VALIGATOR_IMAGE
    - name: Build & Push the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.VALIGATOR_IMAGE }}
    - name: Docker Login
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login --username "${{ github.actor }}" --password-stdin
    - name: Push the Docker Image
      run: docker push ${VALIGATOR_IMAGE}
