name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VALIGATOR_IMAGE: ghcr.io/huk-coburg/apifant-valigator

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate Docker Image Tag
      run: echo "VALIGATOR_TAG=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag ${VALIGATOR_IMAGE}:${VALIGATOR_TAG}
    - name: Tag the Docker Image
      run: docker tag ${VALIGATOR_IMAGE}:${VALIGATOR_TAG} ${VALIGATOR_IMAGE}:latest
    - name: Docker Login
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username "${{ github.actor }}" --password-stdin
    - name: Push CI Tag
      run: docker push ${VALIGATOR_IMAGE}:${VALIGATOR_TAG}
    - name: Push Latest Tag
      run: docker push ${VALIGATOR_IMAGE}:latest
