name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate Docker Image Tag
      run: echo "VALIGATOR_IMAGE=ghcr.io/huk-coburg/apifant-valigator:$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV
    - name: Build & Push the Docker image
      run: docker build . --file Dockerfile --tag ${VALIGATOR_IMAGE}
    - name: Docker Login
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login --username "${{ github.actor }}" --password-stdin
    - name: Push the Docker Image
      run: docker push ${VALIGATOR_IMAGE}
